preprocess:
  max_len: 1024
  min_freq: 5
  is_demo: 0

model:
  model_type: 'GRU'
  embed_size: 64
  hidden_num: 128
  layer_num: 3
  load_checkpoint: ''

train:
  cuda_visible_devices: '1'
  multi_gpu: 0
  batch_size: 128
  lr: 0.0003
  train_steps: 10000
  steps_per_check: 100
  steps_per_checkpoint: 2000
  checkpoint_dir: 'RNN/'

eval:
  submit_file: 'submit.csv'